# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLGeVr5udBp0-fqW5N1IOEf4fsmgmOWb
"""

# Trabajao presentado por: Santiago Carvajal del salon TS7A
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


titanic = sns.load_dataset('titanic')


plt.figure(figsize=(10, 6))
sns.countplot(data=titanic, x='class', hue='survived', palette='pastel')
plt.title('Supervivencia por Clase')
plt.xlabel('Clase')
plt.ylabel('Número de Pasajeros')
plt.legend(title='Supervivió', labels=['No', 'Sí'])
plt.show()


plt.figure(figsize=(10, 6))
sns.histplot(data=titanic[titanic['survived'] == 1]['age'], bins=30, kde=True, color='green')
plt.title('Distribución de Edad de Sobrevivientes')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()


plt.figure(figsize=(10, 6))
sns.countplot(data=titanic, x='sex', hue='survived', palette='pastel')
plt.title('Supervivencia por Género')
plt.xlabel('Género')
plt.ylabel('Número de Pasajeros')
plt.legend(title='Supervivió', labels=['No', 'Sí'])
plt.show()


plt.figure(figsize=(10, 6))
correlation = titanic.corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Mapa de Calor de Correlación')
plt.show()